spring:
  application:
    name: hbtzfx
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cd-cdb-hycofijw.sql.tencentcdb.com:63827/tel
    username: root
    password: wsj@2018
  thymeleaf:
    cache: false

mybatis:
  #实体类所做包
  type-aliases-package: com.hbtzfx.entity
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml

 # log
logging:
  config: classpath:logback-spring.xml
  path: /data/runtimes/log/hbtzfx

